import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "../globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";

const roboto = Kanit({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
    title: "Feedback",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <AuthProvider>
                <body className={roboto.className}>
                    <Navbar />
                    {children}
                    <Toaster />
                </body>
            </AuthProvider>
        </html>
    );
}
